### ISSUE TITLE
I can strangely not scrape since 7 weeks ago

### ISSUE THREAD

**Issue by saskir12** [maforget/ComicRack_AmazonScrapper#6]
So, I am used that it sometimes does or does not work (Amazon.... what else).

But strangely I can not scrape for a little more then 7 weeks. No matter if I tried it over a VPN, directly, the time of day, over WiFi, Ethernet, etc.

I get no results.

So what could I try to make it work? Is there any Firewall rule which a Windows 11 Update may have changed?

**Comment by maforget** [comment]
Do not use the v1 release, use only the nightly. This was fixed already. 

#4 & #5 duplicate.
