### ISSUE TITLE
Scraper no longer shows any values in "title" field in UI when searching/scraping

### ISSUE THREAD

**Issue by nosoop4u** [maforget/ComicRack_AmazonScrapper#7]
As of about a week ago (first week of Dec 2024), the scraper no longer shows any values in the "title" field in the selection screen.  Fields "ASIN" and "Serie" are still shown, but the "title" field is blank for every search result.  Covers are still shown as well, so matching can still be done by cover.

**Comment by maforget** [comment]
Fixed in latest nightly
